all:
	make -C hello/
	make -C abcounter/
	make -C addressbook/
	make -C balance/

clean:
	make -C hello/ clean
	make -C abcounter/ clean
	make -C addressbook/ clean
	make -C balance/ clean

re:
	make -C hello/ re
	make -C abcounter/ re
	make -C addressbook/ re
	make -C balance/ re
